export const CHANGE_PAGE = 'CHANGE_PAGE';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const QUERY_PAGE = 'QUERY_PAGE';
export const SUCCESS_QUERY = 'SUCCESS_QUERY';

export const SNACKBAR_SUCCESS = 'SNACKBAR_SUCCESS';
export const SNACKBAR_CLEAR = 'SNACKBAR_CLEAR';
export const SNACKBAR_ERROR = 'SNACKBAR_ERROR';
export const SNACKBAR_WARNING = 'SNACKBAR_WARNING';
